{
  "status": "SUCCESS",
  "cpu_usage": [
    "26"
  ],
  "stdout": [
    "EPI(k=10,i=  50): cost -6.75E+00, H  6.86E+00, |R|^2 3.43E-03\n",
    "EPI(k=10,i= 100): cost -6.67E+00, H  6.75E+00, |R|^2 3.92E-03\n",
    "EPI(k=10,i= 150): cost -6.27E+00, H  6.67E+00, |R|^2 1.25E-02\n",
    "EPI(k=10,i= 200): cost -6.63E+00, H  6.57E+00, |R|^2 2.02E-02\n",
    "EPI(k=10,i= 250): cost -6.53E+00, H  6.81E+00, |R|^2 8.92E-03\n",
    "EPI(k=10,i= 300): cost -3.01E+00, H  6.76E+00, |R|^2 2.82E-01\n",
    "EPI(k=10,i= 350): cost -6.60E+00, H  6.73E+00, |R|^2 5.83E-03\n",
    "EPI(k=10,i= 400): cost -6.25E+00, H  6.88E+00, |R|^2 2.94E-02\n",
    "EPI(k=10,i= 450): cost -6.69E+00, H  6.99E+00, |R|^2 1.37E-02\n",
    "EPI(k=10,i= 500): cost -6.95E+00, H  7.16E+00, |R|^2 2.09E-02\n",
    "EPI(k=10,i= 550): cost -7.12E+00, H  7.06E+00, |R|^2 6.64E-03\n",
    "EPI(k=10,i= 600): cost -6.30E+00, H  7.00E+00, |R|^2 2.99E-02\n",
    "EPI(k=10,i= 650): cost -6.76E+00, H  6.92E+00, |R|^2 3.08E-03\n",
    "EPI(k=10,i= 700): cost -6.67E+00, H  7.06E+00, |R|^2 1.97E-02\n",
    "EPI(k=10,i= 750): cost -6.42E+00, H  7.09E+00, |R|^2 3.21E-02\n",
    "EPI(k=10,i= 800): cost -6.98E+00, H  6.97E+00, |R|^2 7.38E-03\n",
    "EPI(k=10,i= 850): cost -6.66E+00, H  7.04E+00, |R|^2 2.00E-02\n",
    "EPI(k=10,i= 900): cost -6.41E+00, H  6.87E+00, |R|^2 1.86E-02\n",
    "EPI(k=10,i= 950): cost -6.92E+00, H  7.13E+00, |R|^2 8.92E-03\n",
    "EPI(k=10,i=1000): cost -6.50E+00, H  6.94E+00, |R|^2 1.97E-02\n"
  ],
  "instance": "i-0f4c72ed9511f3f35",
  "reason": [
    "aws s3 sync ./ \"s3://$bucketname/$groupdir/$resultdir/per_hp\""
  ],
  "command": "d7875f78-1019-4996-8488-d71afe12e05a",
  "stderr": [
    "2020-03-18 14:29:02.962235: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-18 14:29:02.962316: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-18 14:29:02.962325: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
    "2020-03-18 14:29:38.395554: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
    "2020-03-18 14:29:39.037550: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
    "2020-03-18 14:29:39.037585: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-74-7): /proc/driver/nvidia/version does not exist\n",
    "2020-03-18 14:29:39.038138: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
    "2020-03-18 14:29:39.139232: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz\n",
    "2020-03-18 14:29:39.140566: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5604efe80420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
    "2020-03-18 14:29:39.140596: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:386: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Use keras.layers.Dense instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Please use `layer.__call__` method instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:222: AffineScalar.__init__ (from tensorflow_probability.python.bijectors.affine_scalar) is deprecated and will be removed after 2020-01-01.\n",
    "Instructions for updating:\n",
    "`AffineScalar` bijector is deprecated; please use `tfb.Shift(loc)(tfb.Scale(...))` instead.\n"
  ],
  "input": "cunninghamlabEPI/inputs/epidata-1584541561/dataset6.json"
}
