{
  "status": "SUCCESS",
  "cpu_usage": [
    "28"
  ],
  "stdout": [
    "EPI(k=10,i=  50): cost -7.56E+00, H  7.92E+00, |R|^2 5.58E-02\n",
    "EPI(k=10,i= 100): cost -7.64E+00, H  8.00E+00, |R|^2 5.93E-02\n",
    "EPI(k=10,i= 150): cost -7.67E+00, H  7.76E+00, |R|^2 1.52E-02\n",
    "EPI(k=10,i= 200): cost -7.70E+00, H  7.87E+00, |R|^2 1.25E-02\n",
    "EPI(k=10,i= 250): cost -7.61E+00, H  7.86E+00, |R|^2 2.70E-02\n",
    "EPI(k=10,i= 300): cost -7.65E+00, H  7.98E+00, |R|^2 5.29E-02\n",
    "EPI(k=10,i= 350): cost -7.62E+00, H  7.88E+00, |R|^2 4.00E-02\n",
    "EPI(k=10,i= 400): cost -7.66E+00, H  7.96E+00, |R|^2 4.79E-02\n",
    "EPI(k=10,i= 450): cost -7.60E+00, H  7.85E+00, |R|^2 3.60E-02\n",
    "EPI(k=10,i= 500): cost -7.63E+00, H  7.86E+00, |R|^2 2.72E-02\n",
    "EPI(k=10,i= 550): cost -7.68E+00, H  7.85E+00, |R|^2 2.39E-02\n",
    "EPI(k=10,i= 600): cost -7.66E+00, H  7.87E+00, |R|^2 3.22E-02\n",
    "EPI(k=10,i= 650): cost -7.62E+00, H  7.93E+00, |R|^2 5.28E-02\n",
    "EPI(k=10,i= 700): cost -7.71E+00, H  7.96E+00, |R|^2 3.52E-02\n",
    "EPI(k=10,i= 750): cost -7.48E+00, H  7.93E+00, |R|^2 7.54E-02\n",
    "EPI(k=10,i= 800): cost -7.57E+00, H  7.77E+00, |R|^2 1.60E-02\n",
    "EPI(k=10,i= 850): cost -7.61E+00, H  7.81E+00, |R|^2 2.29E-02\n",
    "EPI(k=10,i= 900): cost -7.65E+00, H  7.80E+00, |R|^2 2.49E-02\n",
    "EPI(k=10,i= 950): cost -7.59E+00, H  7.84E+00, |R|^2 2.67E-02\n",
    "EPI(k=10,i=1000): cost -7.64E+00, H  7.85E+00, |R|^2 2.99E-02\n"
  ],
  "instance": "i-08c8feaff96a440dc",
  "reason": [
    "aws s3 sync ./ \"s3://$bucketname/$groupdir/$resultdir/per_hp\""
  ],
  "command": "cb424596-f9d0-4782-988c-893a4cf60b04",
  "stderr": [
    "2020-03-18 14:29:02.647650: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-18 14:29:02.647726: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-18 14:29:02.647734: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
    "2020-03-18 14:29:38.371071: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
    "2020-03-18 14:29:39.015066: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
    "2020-03-18 14:29:39.015104: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-72-27): /proc/driver/nvidia/version does not exist\n",
    "2020-03-18 14:29:39.015641: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
    "2020-03-18 14:29:39.108032: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz\n",
    "2020-03-18 14:29:39.108995: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5556c2530420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
    "2020-03-18 14:29:39.109025: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:386: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Use keras.layers.Dense instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Please use `layer.__call__` method instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:222: AffineScalar.__init__ (from tensorflow_probability.python.bijectors.affine_scalar) is deprecated and will be removed after 2020-01-01.\n",
    "Instructions for updating:\n",
    "`AffineScalar` bijector is deprecated; please use `tfb.Shift(loc)(tfb.Scale(...))` instead.\n"
  ],
  "input": "cunninghamlabEPI/inputs/epidata-1584541561/dataset10.json"
}
