{
  "status": "SUCCESS",
  "cpu_usage": [
    "27"
  ],
  "stdout": [
    "EPI(k=10,i=  50): cost -7.34E+00, H  7.46E+00, |R|^2 1.04E-02\n",
    "EPI(k=10,i= 100): cost -7.11E+00, H  7.53E+00, |R|^2 3.41E-02\n",
    "EPI(k=10,i= 150): cost -6.91E+00, H  7.48E+00, |R|^2 5.76E-02\n",
    "EPI(k=10,i= 200): cost -7.11E+00, H  7.45E+00, |R|^2 2.90E-02\n",
    "EPI(k=10,i= 250): cost -6.90E+00, H  7.52E+00, |R|^2 6.48E-02\n",
    "EPI(k=10,i= 300): cost -6.87E+00, H  7.43E+00, |R|^2 7.45E-02\n",
    "EPI(k=10,i= 350): cost -7.04E+00, H  7.48E+00, |R|^2 4.15E-02\n",
    "EPI(k=10,i= 400): cost -7.25E+00, H  7.38E+00, |R|^2 1.10E-02\n",
    "EPI(k=10,i= 450): cost -6.90E+00, H  7.41E+00, |R|^2 6.04E-02\n",
    "EPI(k=10,i= 500): cost -6.95E+00, H  7.60E+00, |R|^2 7.53E-02\n",
    "EPI(k=10,i= 550): cost -7.12E+00, H  7.49E+00, |R|^2 2.60E-02\n",
    "EPI(k=10,i= 600): cost -6.61E+00, H  7.39E+00, |R|^2 1.12E-01\n",
    "EPI(k=10,i= 650): cost -7.20E+00, H  7.54E+00, |R|^2 2.95E-02\n",
    "EPI(k=10,i= 700): cost -6.96E+00, H  7.46E+00, |R|^2 4.77E-02\n",
    "EPI(k=10,i= 750): cost -7.00E+00, H  7.51E+00, |R|^2 5.59E-02\n",
    "EPI(k=10,i= 800): cost -7.00E+00, H  7.48E+00, |R|^2 4.63E-02\n",
    "EPI(k=10,i= 850): cost -7.27E+00, H  7.51E+00, |R|^2 1.84E-02\n",
    "EPI(k=10,i= 900): cost -6.81E+00, H  7.49E+00, |R|^2 9.26E-02\n",
    "EPI(k=10,i= 950): cost -7.13E+00, H  7.38E+00, |R|^2 1.81E-02\n",
    "EPI(k=10,i=1000): cost -6.94E+00, H  7.41E+00, |R|^2 4.49E-02\n"
  ],
  "instance": "i-00dd7cc861255ed32",
  "reason": [
    "aws s3 sync ./ \"s3://$bucketname/$groupdir/$resultdir/per_hp\""
  ],
  "command": "98e72754-f3d7-4a82-9630-22e3d2598d4a",
  "stderr": [
    "2020-03-10 14:02:12.492875: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-10 14:02:12.492987: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-10 14:02:12.492997: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
    "2020-03-10 14:02:47.139990: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
    "2020-03-10 14:02:47.557944: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
    "2020-03-10 14:02:47.557992: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-66-188): /proc/driver/nvidia/version does not exist\n",
    "2020-03-10 14:02:47.558560: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
    "2020-03-10 14:02:47.705603: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500000000 Hz\n",
    "2020-03-10 14:02:47.706620: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5630bc81f420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
    "2020-03-10 14:02:47.706642: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:386: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Use keras.layers.Dense instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Please use `layer.__call__` method instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:222: AffineScalar.__init__ (from tensorflow_probability.python.bijectors.affine_scalar) is deprecated and will be removed after 2020-01-01.\n",
    "Instructions for updating:\n",
    "`AffineScalar` bijector is deprecated; please use `tfb.Shift(loc)(tfb.Scale(...))` instead.\n"
  ],
  "input": "cunninghamlabEPI/inputs/epidata/dataset4.json"
}
