{
  "status": "SUCCESS",
  "cpu_usage": [
    "28"
  ],
  "stdout": [
    "EPI(k=10,i=  50): cost -7.37E+00, H  7.66E+00, |R|^2 6.09E-02\n",
    "EPI(k=10,i= 100): cost -7.26E+00, H  7.53E+00, |R|^2 2.64E-02\n",
    "EPI(k=10,i= 150): cost -7.57E+00, H  7.69E+00, |R|^2 1.63E-02\n",
    "EPI(k=10,i= 200): cost -7.55E+00, H  7.69E+00, |R|^2 2.69E-02\n",
    "EPI(k=10,i= 250): cost -7.51E+00, H  7.74E+00, |R|^2 1.25E-02\n",
    "EPI(k=10,i= 300): cost -7.51E+00, H  7.67E+00, |R|^2 1.61E-02\n",
    "EPI(k=10,i= 350): cost -7.29E+00, H  7.64E+00, |R|^2 4.56E-02\n",
    "EPI(k=10,i= 400): cost -7.60E+00, H  7.57E+00, |R|^2 7.80E-03\n",
    "EPI(k=10,i= 450): cost -7.57E+00, H  7.77E+00, |R|^2 3.18E-02\n",
    "EPI(k=10,i= 500): cost -7.23E+00, H  7.81E+00, |R|^2 9.82E-02\n",
    "EPI(k=10,i= 550): cost -7.62E+00, H  7.68E+00, |R|^2 6.45E-03\n",
    "EPI(k=10,i= 600): cost -7.59E+00, H  7.78E+00, |R|^2 1.21E-02\n",
    "EPI(k=10,i= 650): cost -7.54E+00, H  7.66E+00, |R|^2 2.98E-02\n",
    "EPI(k=10,i= 700): cost -7.29E+00, H  7.51E+00, |R|^2 2.22E-02\n",
    "EPI(k=10,i= 750): cost -7.46E+00, H  7.66E+00, |R|^2 1.39E-02\n",
    "EPI(k=10,i= 800): cost -7.54E+00, H  7.69E+00, |R|^2 1.14E-02\n",
    "EPI(k=10,i= 850): cost -7.55E+00, H  7.91E+00, |R|^2 4.54E-02\n",
    "EPI(k=10,i= 900): cost -7.56E+00, H  7.73E+00, |R|^2 1.34E-02\n",
    "EPI(k=10,i= 950): cost -7.59E+00, H  7.65E+00, |R|^2 1.65E-02\n",
    "EPI(k=10,i=1000): cost -7.29E+00, H  7.76E+00, |R|^2 5.14E-02\n"
  ],
  "instance": "i-07b4a22606666cf73",
  "reason": [
    "aws s3 sync ./ \"s3://$bucketname/$groupdir/$resultdir/per_hp\""
  ],
  "command": "791d1047-153e-47e3-a176-0487fb91ed2b",
  "stderr": [
    "2020-03-10 14:02:12.506673: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-10 14:02:12.506751: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-10 14:02:12.506759: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
    "2020-03-10 14:02:47.163243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
    "2020-03-10 14:02:47.578774: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
    "2020-03-10 14:02:47.578819: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-66-57): /proc/driver/nvidia/version does not exist\n",
    "2020-03-10 14:02:47.579319: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
    "2020-03-10 14:02:47.728663: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500000000 Hz\n",
    "2020-03-10 14:02:47.729643: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ee78f43420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
    "2020-03-10 14:02:47.729663: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:386: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Use keras.layers.Dense instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Please use `layer.__call__` method instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:222: AffineScalar.__init__ (from tensorflow_probability.python.bijectors.affine_scalar) is deprecated and will be removed after 2020-01-01.\n",
    "Instructions for updating:\n",
    "`AffineScalar` bijector is deprecated; please use `tfb.Shift(loc)(tfb.Scale(...))` instead.\n"
  ],
  "input": "cunninghamlabEPI/inputs/epidata/dataset8.json"
}
