{
  "status": "SUCCESS",
  "cpu_usage": [
    "27"
  ],
  "stdout": [
    "EPI(k=10,i=  50): cost -7.06E+00, H  7.35E+00, |R|^2 2.22E-02\n",
    "EPI(k=10,i= 100): cost -6.73E+00, H  7.29E+00, |R|^2 4.09E-02\n",
    "EPI(k=10,i= 150): cost -6.94E+00, H  7.22E+00, |R|^2 1.73E-02\n",
    "EPI(k=10,i= 200): cost -7.00E+00, H  7.22E+00, |R|^2 1.22E-02\n",
    "EPI(k=10,i= 250): cost -7.18E+00, H  7.24E+00, |R|^2 1.74E-03\n",
    "EPI(k=10,i= 300): cost -6.72E+00, H  7.14E+00, |R|^2 2.40E-02\n",
    "EPI(k=10,i= 350): cost -6.74E+00, H  7.13E+00, |R|^2 2.29E-02\n",
    "EPI(k=10,i= 400): cost -7.15E+00, H  7.11E+00, |R|^2 2.10E-03\n",
    "EPI(k=10,i= 450): cost -6.66E+00, H  7.31E+00, |R|^2 5.01E-02\n",
    "EPI(k=10,i= 500): cost -6.87E+00, H  7.39E+00, |R|^2 3.37E-02\n",
    "EPI(k=10,i= 550): cost -6.92E+00, H  7.29E+00, |R|^2 1.95E-02\n",
    "EPI(k=10,i= 600): cost -7.16E+00, H  7.13E+00, |R|^2 1.50E-02\n",
    "EPI(k=10,i= 650): cost -6.69E+00, H  7.33E+00, |R|^2 5.95E-02\n",
    "EPI(k=10,i= 700): cost -7.05E+00, H  7.28E+00, |R|^2 1.73E-02\n",
    "EPI(k=10,i= 750): cost -7.18E+00, H  7.28E+00, |R|^2 3.91E-03\n",
    "EPI(k=10,i= 800): cost -7.06E+00, H  7.20E+00, |R|^2 5.33E-03\n",
    "EPI(k=10,i= 850): cost -7.11E+00, H  7.31E+00, |R|^2 8.68E-03\n",
    "EPI(k=10,i= 900): cost -7.24E+00, H  7.29E+00, |R|^2 1.62E-02\n",
    "EPI(k=10,i= 950): cost -6.80E+00, H  7.24E+00, |R|^2 3.17E-02\n",
    "EPI(k=10,i=1000): cost -7.16E+00, H  7.21E+00, |R|^2 6.18E-03\n"
  ],
  "instance": "i-009a82e63c6dec348",
  "reason": [
    "aws s3 sync ./ \"s3://$bucketname/$groupdir/$resultdir/per_hp\""
  ],
  "command": "4da17b39-c46d-4d3f-b87f-4b98c2b14c32",
  "stderr": [
    "2020-03-18 14:29:02.658804: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-18 14:29:02.658900: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-18 14:29:02.658912: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
    "2020-03-18 14:29:38.387684: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
    "2020-03-18 14:29:39.034095: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
    "2020-03-18 14:29:39.034136: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-69-1): /proc/driver/nvidia/version does not exist\n",
    "2020-03-18 14:29:39.034707: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
    "2020-03-18 14:29:39.140123: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499990000 Hz\n",
    "2020-03-18 14:29:39.141324: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x563f58626420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
    "2020-03-18 14:29:39.141349: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:386: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Use keras.layers.Dense instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Please use `layer.__call__` method instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:222: AffineScalar.__init__ (from tensorflow_probability.python.bijectors.affine_scalar) is deprecated and will be removed after 2020-01-01.\n",
    "Instructions for updating:\n",
    "`AffineScalar` bijector is deprecated; please use `tfb.Shift(loc)(tfb.Scale(...))` instead.\n"
  ],
  "input": "cunninghamlabEPI/inputs/epidata-1584541561/dataset3.json"
}
