{
  "status": "SUCCESS",
  "cpu_usage": [
    "27"
  ],
  "stdout": [
    "EPI(k=10,i=  50): cost -7.46E+00, H  7.63E+00, |R|^2 1.01E-02\n",
    "EPI(k=10,i= 100): cost -7.43E+00, H  7.60E+00, |R|^2 1.23E-02\n",
    "EPI(k=10,i= 150): cost -7.32E+00, H  7.46E+00, |R|^2 1.72E-02\n",
    "EPI(k=10,i= 200): cost -7.25E+00, H  7.49E+00, |R|^2 1.66E-02\n",
    "EPI(k=10,i= 250): cost -7.41E+00, H  7.57E+00, |R|^2 1.43E-02\n",
    "EPI(k=10,i= 300): cost -7.40E+00, H  7.50E+00, |R|^2 4.99E-03\n",
    "EPI(k=10,i= 350): cost -7.39E+00, H  7.44E+00, |R|^2 9.70E-03\n",
    "EPI(k=10,i= 400): cost -7.17E+00, H  7.43E+00, |R|^2 2.44E-02\n",
    "EPI(k=10,i= 450): cost -7.39E+00, H  7.42E+00, |R|^2 6.87E-03\n",
    "EPI(k=10,i= 500): cost -7.39E+00, H  7.56E+00, |R|^2 2.20E-02\n",
    "EPI(k=10,i= 550): cost -7.37E+00, H  7.47E+00, |R|^2 7.24E-03\n",
    "EPI(k=10,i= 600): cost -7.27E+00, H  7.42E+00, |R|^2 8.37E-03\n",
    "EPI(k=10,i= 650): cost -7.48E+00, H  7.52E+00, |R|^2 6.06E-03\n",
    "EPI(k=10,i= 700): cost -7.50E+00, H  7.54E+00, |R|^2 9.20E-03\n",
    "EPI(k=10,i= 750): cost -7.46E+00, H  7.52E+00, |R|^2 5.43E-03\n",
    "EPI(k=10,i= 800): cost -7.23E+00, H  7.46E+00, |R|^2 1.59E-02\n",
    "EPI(k=10,i= 850): cost -7.30E+00, H  7.69E+00, |R|^2 2.91E-02\n",
    "EPI(k=10,i= 900): cost -7.20E+00, H  7.66E+00, |R|^2 3.70E-02\n",
    "EPI(k=10,i= 950): cost -7.47E+00, H  7.58E+00, |R|^2 9.30E-03\n",
    "EPI(k=10,i=1000): cost -7.47E+00, H  7.66E+00, |R|^2 9.26E-03\n"
  ],
  "instance": "i-0cfcbfee15c99fcd5",
  "reason": [
    "aws s3 sync ./ \"s3://$bucketname/$groupdir/$resultdir/per_hp\""
  ],
  "command": "886fc07d-60a6-4e20-be02-656c6bb1bdbe",
  "stderr": [
    "2020-03-10 14:02:12.502229: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-10 14:02:12.502325: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
    "2020-03-10 14:02:12.502337: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
    "2020-03-10 14:02:47.164172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
    "2020-03-10 14:02:47.592368: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
    "2020-03-10 14:02:47.592412: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-77-155): /proc/driver/nvidia/version does not exist\n",
    "2020-03-10 14:02:47.592886: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
    "2020-03-10 14:02:47.724775: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz\n",
    "2020-03-10 14:02:47.725907: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5562cfdc7420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
    "2020-03-10 14:02:47.725936: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:386: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Use keras.layers.Dense instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\n",
    "Instructions for updating:\n",
    "Please use `layer.__call__` method instead.\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/real_nvp.py:222: AffineScalar.__init__ (from tensorflow_probability.python.bijectors.affine_scalar) is deprecated and will be removed after 2020-01-01.\n",
    "Instructions for updating:\n",
    "`AffineScalar` bijector is deprecated; please use `tfb.Shift(loc)(tfb.Scale(...))` instead.\n"
  ],
  "input": "cunninghamlabEPI/inputs/epidata/dataset1.json"
}
